# Generated by Django 6.0.5 on 2026-05-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la banque')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug (URL de connexion)')),
                ('logo', models.ImageField(upload_to='banks/logos/', verbose_name='Logo')),
                ('tagline', models.CharField(blank=True, max_length=300, verbose_name='Slogan')),
                ('address', models.TextField(verbose_name='Adresse du siège')),
                ('phone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email officiel')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('swift', models.CharField(max_length=11, verbose_name='Code SWIFT/BIC')),
                ('bank_code', models.CharField(max_length=10, verbose_name='Code banque')),
                ('country', models.CharField(default='France', max_length=100, verbose_name='Pays siège')),
                ('color_primary', models.CharField(default='#1a3a5c', max_length=7, verbose_name='Couleur primaire')),
                ('color_secondary', models.CharField(default='#2ecc71', max_length=7, verbose_name='Couleur secondaire')),
                ('color_accent', models.CharField(default='#f39c12', max_length=7, verbose_name='Couleur accent')),
                ('color_text_on_primary', models.CharField(default='#ffffff', max_length=7, verbose_name='Texte sur couleur primaire')),
                ('color_background', models.CharField(default='#f8f9fa', max_length=7, verbose_name='Couleur arrière-plan')),
                ('color_card', models.CharField(default='#1a3a5c', max_length=7, verbose_name='Couleur carte bancaire')),
                ('color_card_text', models.CharField(default='#ffffff', max_length=7, verbose_name='Texte sur carte bancaire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Banque active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banque',
                'verbose_name_plural': 'Banques',
                'ordering': ['name'],
            },
        ),
    ]
