# Generated by Django 6.0.5 on 2026-06-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='favicon',
            field=models.FileField(blank=True, null=True, upload_to='banks/favicons/', verbose_name='Favicon (icône onglet)'),
        ),
        migrations.AddField(
            model_name='bank',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Description SEO (160 car. max)'),
        ),
        migrations.AddField(
            model_name='bank',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='banks/og/', verbose_name='Image de partage (Open Graph)'),
        ),
    ]
