# Generated by Django 6.0.5 on 2026-06-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0004_prefill_cm_seo_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='favicon',
            field=models.FileField(blank=True, null=True, upload_to='banks/favicons/', verbose_name='Favicon (fichier uploadé)'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Banque active'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='banks/og/', verbose_name='Image Open Graph (fichier uploadé)'),
        ),
    ]
