# Generated by Django 6.0.5 on 2026-06-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_security_constraints_and_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL directe vers le logo affiché sur le site (prioritaire sur le fichier uploadé).', verbose_name='URL logo externe'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='favicon_url',
            field=models.URLField(blank=True, help_text='URL directe vers le favicon (onglet navigateur uniquement).', verbose_name='URL favicon externe'),
        ),
    ]
