# Generated by Django 6.0.5 on 2026-05-23 18:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('account_id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Identifiant')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('courant', 'Compte courant'), ('epargne', 'Compte épargne')], default='courant', max_length=20, verbose_name='Type de compte')),
                ('is_primary', models.BooleanField(default=True, verbose_name='Compte principal')),
                ('account_id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Identifiant du compte')),
                ('rib', models.CharField(max_length=34, unique=True, verbose_name='RIB / IBAN')),
                ('plain_password', models.CharField(blank=True, max_length=100, verbose_name='Mot de passe initial (visible admin uniquement)')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Adresse email')),
                ('phone', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('country', models.CharField(max_length=100, verbose_name='Pays')),
                ('address', models.TextField(verbose_name='Adresse géographique')),
                ('birth_date', models.DateField(verbose_name='Date de naissance')),
                ('currency', models.CharField(max_length=3, verbose_name='Devise')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Solde')),
                ('status', models.CharField(choices=[('active', 'Compte actif'), ('blocked', 'Compte bloqué')], db_index=True, default='active', max_length=10, verbose_name='Statut du compte')),
                ('block_reason', models.TextField(blank=True, verbose_name='Motif du blocage')),
                ('unblock_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Frais de déblocage')),
                ('manager_name', models.CharField(max_length=200, verbose_name='Nom du gestionnaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='banks.bank', verbose_name='Banque')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Compte bancaire',
                'verbose_name_plural': 'Comptes bancaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('account_created', 'Compte créé'), ('account_blocked', 'Compte bloqué'), ('account_unblocked', 'Compte débloqué'), ('transfer_created', 'Virement créé'), ('transfer_validated', 'Virement validé'), ('transfer_rejected', 'Virement rejeté'), ('balance_updated', 'Solde mis à jour'), ('login', 'Connexion'), ('password_changed', 'Mot de passe modifié')], db_index=True, max_length=30)),
                ('actor', models.CharField(max_length=200, verbose_name='Acteur (admin/client)')),
                ('description', models.TextField()),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='banks.bank')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.bankaccount')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('account_number', models.CharField(max_length=34, verbose_name='Numéro de compte (IBAN)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email du bénéficiaire')),
                ('bank_name', models.CharField(max_length=200, verbose_name='Nom de la banque du bénéficiaire')),
                ('bank_swift', models.CharField(blank=True, max_length=11, verbose_name='SWIFT/BIC de la banque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='accounts.bankaccount', verbose_name='Compte source')),
            ],
            options={
                'verbose_name': 'Bénéficiaire',
                'verbose_name_plural': 'Bénéficiaires',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(db_index=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('success', models.BooleanField(default=False)),
                ('bank_slug', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tentative de connexion',
                'verbose_name_plural': 'Tentatives de connexion',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address', 'created_at'], name='accounts_lo_ip_addr_71e387_idx'), models.Index(fields=['account_id', 'created_at'], name='accounts_lo_account_f484df_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['bank', 'status'], name='accounts_ba_bank_id_e1fef5_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['bank', 'account_id'], name='accounts_ba_bank_id_5e113c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['bank', 'created_at'], name='accounts_au_bank_id_b83807_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['account', 'action'], name='accounts_au_account_6424f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='beneficiary',
            unique_together={('account', 'account_number')},
        ),
    ]
