# Generated by Django 6.0.5 on 2026-05-23 18:12

import django.db.models.deletion
import transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=transactions.models.generate_reference, max_length=20, unique=True, verbose_name='Référence')),
                ('transaction_type', models.CharField(choices=[('transfer_out', 'Virement sortant'), ('transfer_in', 'Virement entrant'), ('withdrawal', 'Retrait au guichet'), ('deposit', 'Dépôt en banque'), ('payment', 'Paiement de facture')], max_length=20, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant')),
                ('currency', models.CharField(max_length=3, verbose_name='Devise')),
                ('description', models.TextField(blank=True, verbose_name='Description / Libellé')),
                ('status', models.CharField(choices=[('pending', 'En cours de validation'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='validated', max_length=15, verbose_name='Statut')),
                ('beneficiary_name', models.CharField(blank=True, max_length=200, verbose_name='Nom du bénéficiaire (manuel)')),
                ('beneficiary_iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN bénéficiaire (manuel)')),
                ('beneficiary_email', models.EmailField(blank=True, max_length=254, verbose_name='Email bénéficiaire (manuel)')),
                ('beneficiary_bank', models.CharField(blank=True, max_length=200, verbose_name='Banque bénéficiaire (manuel)')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motif du rejet')),
                ('rejection_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Frais de redirection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation/rejet')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.bankaccount', verbose_name='Compte')),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.beneficiary', verbose_name='Bénéficiaire')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
