# Generated by Django 6.0.5 on 2026-06-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_security_constraints_and_indexes'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['account', 'is_read', '-created_at'], name='notif_account_unread_idx'),
        ),
    ]
